export const trustLeaseControllerAbi = [
  {
    type: 'function',
    name: 'issueLease',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'leaseId', type: 'string' },
      { name: 'consumerName', type: 'string' },
      { name: 'wallet', type: 'address' },
      { name: 'baseAsset', type: 'string' },
      { name: 'expiresAt', type: 'uint64' },
      { name: 'perTxUsd6', type: 'uint128' },
      { name: 'dailyBudgetUsd6', type: 'uint128' },
      { name: 'policyHash', type: 'bytes32' },
      { name: 'notesHash', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'setLeaseStatus',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'leaseId', type: 'string' },
      { name: 'status', type: 'uint8' },
      { name: 'noteHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setOperatorMode',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'operatorName', type: 'string' },
      { name: 'mode', type: 'uint8' },
      { name: 'noteHash', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'anchorReceipt',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'leaseId', type: 'string' },
      { name: 'requestId', type: 'string' },
      { name: 'consumerName', type: 'string' },
      { name: 'outcome', type: 'uint8' },
      { name: 'executionStatus', type: 'uint8' },
      { name: 'spentUsd6', type: 'uint128' },
      { name: 'txHash', type: 'bytes32' },
      { name: 'proofHash', type: 'bytes32' },
      { name: 'artifactUri', type: 'string' },
    ],
    outputs: [{ name: '', type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'getActiveLeaseByConsumer',
    stateMutability: 'view',
    inputs: [{ name: 'consumerName', type: 'string' }],
    outputs: [
      { name: 'exists', type: 'bool' },
      { name: 'leaseId', type: 'string' },
      { name: 'wallet', type: 'address' },
      { name: 'consumerName_', type: 'string' },
      { name: 'baseAsset', type: 'string' },
      { name: 'issuedAt', type: 'uint64' },
      { name: 'expiresAt', type: 'uint64' },
      { name: 'status', type: 'uint8' },
      { name: 'perTxUsd6', type: 'uint128' },
      { name: 'dailyBudgetUsd6', type: 'uint128' },
      { name: 'spentTodayUsd6', type: 'uint128' },
      { name: 'spentWindowStartedAt', type: 'uint64' },
      { name: 'remainingDailyUsd6', type: 'uint128' },
      { name: 'policyHash', type: 'bytes32' },
      { name: 'notesHash', type: 'bytes32' },
    ],
  },
  {
    type: 'function',
    name: 'getOperator',
    stateMutability: 'view',
    inputs: [{ name: 'operatorName', type: 'string' }],
    outputs: [
      { name: 'exists', type: 'bool' },
      { name: 'operatorName_', type: 'string' },
      { name: 'mode', type: 'uint8' },
      { name: 'updatedAt', type: 'uint64' },
      { name: 'noteHash', type: 'bytes32' },
      { name: 'updater', type: 'address' },
    ],
  },
  {
    type: 'function',
    name: 'getLatestReceiptByConsumer',
    stateMutability: 'view',
    inputs: [{ name: 'consumerName', type: 'string' }],
    outputs: [
      { name: 'exists', type: 'bool' },
      { name: 'leaseId', type: 'string' },
      { name: 'requestId', type: 'string' },
      { name: 'consumerName_', type: 'string' },
      { name: 'outcome', type: 'uint8' },
      { name: 'executionStatus', type: 'uint8' },
      { name: 'spentUsd6', type: 'uint128' },
      { name: 'txHash', type: 'bytes32' },
      { name: 'proofHash', type: 'bytes32' },
      { name: 'artifactUri', type: 'string' },
      { name: 'timestamp', type: 'uint64' },
    ],
  },
  {
    type: 'function',
    name: 'canExecute',
    stateMutability: 'view',
    inputs: [
      { name: 'leaseId', type: 'string' },
      { name: 'requestedUsd6', type: 'uint128' },
    ],
    outputs: [
      { name: 'allowed', type: 'bool' },
      { name: 'resolvedStatus', type: 'uint8' },
      { name: 'remainingDailyUsd6', type: 'uint128' },
    ],
  },
] as const;
